const data = [
  {
    id: "1",
    name: "Weight Loss",
    img: "",
    price: "5000",
    duration: "6 Month",
    description: "",
  },
  {
    id: "2",
    name: "Weight Gain",
    img: "",
    price: "5000",
    duration: "4 Month",
    description: "",
  },
  {
    id: "3",
    name: "full body workout",
    img: "",
    price: "8000",
    duration: "6 Month",
    description: "",
  },
  {
    id: "4",
    name: "body fit exercise",
    img: "",
    price: "6000",
    duration: "4 Month",
    description: "",
  },
  {
    id: "5",
    name: "six pack exercise",
    img: "",
    price: "5000",
    duration: "4 Month",
    description: "",
  },
  {
    id: "6",
    name: "belly fat loss exercise",
    img: "",
    price: "4000",
    duration: "4 Month",
    description: "",
  },
];
